<?xml version="1.0" encoding="utf-8"?><Database Name="DBProject1617" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Paolo\Desktop\dbproject-1617\DBProject\database\DBProject1617.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="DBProject.Properties.Settings" SettingsPropertyName="DBProject1617ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoCliente" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="CodiceFiscale" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Cognome" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CittàNascita" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ProvinciaNascita" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PartitaIVA" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="RagioneSociale" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Recapito1" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Recapito2" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IndirizzoEmail1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IndirizzoEmail2" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Indirizzo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Città" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_ContrattoVendita" Member="ContrattoVendita" ThisKey="Id" OtherKey="Cliente" Type="ContrattoVendita" />
    </Type>
  </Table>
  <Table Name="dbo.ContrattoVendita" Member="ContrattoVendita">
    <Type Name="ContrattoVendita">
      <Column Name="Numero" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ImportoComplessivo" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="ModalitàPagamento" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="ContrattoVendita_RataCliente" Member="RataCliente" ThisKey="Numero" OtherKey="Contratto" Type="RataCliente" />
      <Association Name="ContrattoVendita_Trasporto" Member="Trasporto" ThisKey="Numero" OtherKey="ContrattoNumero" Type="Trasporto" />
      <Association Name="ContrattoVendita_VeicoloVenduto" Member="VeicoloVenduto" ThisKey="Numero" OtherKey="Contratto" Type="VeicoloVenduto" />
      <Association Name="Cliente_ContrattoVendita" Member="Cliente1" ThisKey="Cliente" OtherKey="Id" Type="Cliente" IsForeignKey="true" />
      <Association Name="NostreModalitàPagamento_ContrattoVendita" Member="NostreModalitàPagamento" ThisKey="ModalitàPagamento" OtherKey="Da" Type="NostreModalitàPagamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Corriere" Member="Corriere">
    <Type Name="Corriere">
      <Column Name="PartitaIVA" Type="System.String" DbType="Char(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RagioneSociale" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Indirizzo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Città" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="Recapito1" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Recapito2" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="IndirizzoEmail1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IndirizzoEmail2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Corriere_Trasporto" Member="Trasporto" ThisKey="PartitaIVA" OtherKey="Corriere" Type="Trasporto" />
    </Type>
  </Table>
  <Table Name="dbo.Dotazione" Member="Dotazione">
    <Type Name="Dotazione">
      <Column Name="Optional" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Veicolo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Optional_Dotazione" Member="Optional1" ThisKey="Optional" OtherKey="Codice" Type="Optional" IsForeignKey="true" />
      <Association Name="VeicoloVenduto_Dotazione" Member="VeicoloVenduto" ThisKey="Veicolo" OtherKey="Id" Type="VeicoloVenduto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FatturaAcquisto" Member="FatturaAcquisto">
    <Type Name="FatturaAcquisto">
      <Column Name="Fornitore" Type="System.String" DbType="Char(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Numero" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ordine" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ImportoComplessivo" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="ModPagamentoFornitore" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="ModPagamentoDa" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="FatturaAcquisto_Rata" Member="Rata" ThisKey="Fornitore,Numero" OtherKey="FornitoreFattura,NumeroFattura" Type="Rata" />
      <Association Name="Fornitore_FatturaAcquisto" Member="Fornitore1" ThisKey="Fornitore" OtherKey="PartitaIVA" Type="Fornitore" IsForeignKey="true" />
      <Association Name="ModalitàPagamento_FatturaAcquisto" Member="ModalitàPagamento" ThisKey="ModPagamentoFornitore,ModPagamentoDa" OtherKey="Fornitore,Da" Type="ModalitàPagamento" IsForeignKey="true" />
      <Association Name="Ordine_FatturaAcquisto" Member="Ordine1" ThisKey="Ordine" OtherKey="Id" Type="Ordine" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fornitore" Member="Fornitore">
    <Type Name="Fornitore">
      <Column Name="PartitaIVA" Type="System.String" DbType="Char(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CasaProduttrice" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="FornitoreRicambi" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="RagioneSociale" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Recapito1" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Recapito2" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="IndirizzoEmail1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IndirizzoEmail2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Indirizzo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Città" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="Fornitore_FatturaAcquisto" Member="FatturaAcquisto" ThisKey="PartitaIVA" OtherKey="Fornitore" Type="FatturaAcquisto" />
      <Association Name="Fornitore_ModalitàPagamento" Member="ModalitàPagamento" ThisKey="PartitaIVA" OtherKey="Fornitore" Type="ModalitàPagamento" />
      <Association Name="Fornitore_ModelloVeicolo" Member="ModelloVeicolo" ThisKey="PartitaIVA" OtherKey="CasaProduttrice" Type="ModelloVeicolo" />
      <Association Name="Fornitore_Ordine" Member="Ordine" ThisKey="PartitaIVA" OtherKey="Fornitore" Type="Ordine" />
      <Association Name="Fornitore_Ricambio" Member="Ricambio" ThisKey="PartitaIVA" OtherKey="Fornitore" Type="Ricambio" />
    </Type>
  </Table>
  <Table Name="dbo.Giacenza" Member="Giacenza">
    <Type Name="Giacenza">
      <Column Name="Ricambio" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Numero" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Quantità" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Column Name="Causale" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Ricambio_Giacenza" Member="Ricambio1" ThisKey="Ricambio" OtherKey="Codice" Type="Ricambio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ModalitàPagamento" Member="ModalitàPagamento">
    <Type Name="ModalitàPagamento">
      <Column Name="Fornitore" Type="System.String" DbType="Char(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Da" Type="System.Single" DbType="Real NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="A" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Periodicità" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TassoInteresse" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="NumeroRate" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Association Name="ModalitàPagamento_FatturaAcquisto" Member="FatturaAcquisto" ThisKey="Fornitore,Da" OtherKey="ModPagamentoFornitore,ModPagamentoDa" Type="FatturaAcquisto" />
      <Association Name="Fornitore_ModalitàPagamento" Member="Fornitore1" ThisKey="Fornitore" OtherKey="PartitaIVA" Type="Fornitore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ModelloVeicolo" Member="ModelloVeicolo">
    <Type Name="ModelloVeicolo">
      <Column Name="Nome" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Anno" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CasaProduttrice" Type="System.String" DbType="Char(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ModelloVeicolo_VeicoloCatalogo" Member="VeicoloCatalogo" ThisKey="Nome,Anno,CasaProduttrice" OtherKey="NomeModello,AnnoModello,CasaProduttrice" Type="VeicoloCatalogo" />
      <Association Name="Fornitore_ModelloVeicolo" Member="Fornitore" ThisKey="CasaProduttrice" OtherKey="PartitaIVA" Type="Fornitore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NostreModalitàPagamento" Member="NostreModalitàPagamento">
    <Type Name="NostreModalitàPagamento">
      <Column Name="Da" Type="System.Single" DbType="Real NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="A" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Periodicità" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TassoInteresse" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="NumerRate" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Association Name="NostreModalitàPagamento_ContrattoVendita" Member="ContrattoVendita" ThisKey="Da" OtherKey="ModalitàPagamento" Type="ContrattoVendita" />
    </Type>
  </Table>
  <Table Name="dbo.Optional" Member="Optional">
    <Type Name="Optional">
      <Column Name="Codice" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Prezzo" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Optional_Dotazione" Member="Dotazione" ThisKey="Codice" OtherKey="Optional" Type="Dotazione" />
      <Association Name="Optional_Supporto" Member="Supporto" ThisKey="Codice" OtherKey="Optional" Type="Supporto" />
    </Type>
  </Table>
  <Table Name="dbo.Ordine" Member="Ordine">
    <Type Name="Ordine">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoOrdine" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="DataOrdine" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataConsegnaPrevista" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataConsegna" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fornitore" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Association Name="Ordine_FatturaAcquisto" Member="FatturaAcquisto" ThisKey="Id" OtherKey="Ordine" Type="FatturaAcquisto" />
      <Association Name="Ordine_OrdineRicambio" Member="OrdineRicambio" ThisKey="Id" OtherKey="Ordine" Type="OrdineRicambio" />
      <Association Name="Ordine_OrdineVeicolo" Member="OrdineVeicolo" ThisKey="Id" OtherKey="Ordine" Type="OrdineVeicolo" />
      <Association Name="Fornitore_Ordine" Member="Fornitore1" ThisKey="Fornitore" OtherKey="PartitaIVA" Type="Fornitore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdineRicambio" Member="OrdineRicambio">
    <Type Name="OrdineRicambio">
      <Column Name="Ordine" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ricambio" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantità" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Column Name="PrezzoUnitario" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Ordine_OrdineRicambio" Member="Ordine1" ThisKey="Ordine" OtherKey="Id" Type="Ordine" IsForeignKey="true" />
      <Association Name="Ricambio_OrdineRicambio" Member="Ricambio1" ThisKey="Ricambio" OtherKey="Codice" Type="Ricambio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdineVeicolo" Member="OrdineVeicolo">
    <Type Name="OrdineVeicolo">
      <Column Name="Veicolo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PrezzoFornitore" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Ordine" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Ordine_OrdineVeicolo" Member="Ordine1" ThisKey="Ordine" OtherKey="Id" Type="Ordine" IsForeignKey="true" />
      <Association Name="VeicoloVenduto_OrdineVeicolo" Member="VeicoloVenduto" ThisKey="Veicolo" OtherKey="Id" Type="VeicoloVenduto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rata" Member="Rata">
    <Type Name="Rata">
      <Column Name="FornitoreFattura" Type="System.String" DbType="Char(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NumeroFattura" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Scadenza" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Importo" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="DataPagamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="FatturaAcquisto_Rata" Member="FatturaAcquisto" ThisKey="FornitoreFattura,NumeroFattura" OtherKey="Fornitore,Numero" Type="FatturaAcquisto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RataCliente" Member="RataCliente">
    <Type Name="RataCliente">
      <Column Name="Contratto" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Scadenza" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Importo" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="DataPagamento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="ContrattoVendita_RataCliente" Member="ContrattoVendita" ThisKey="Contratto" OtherKey="Numero" Type="ContrattoVendita" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Referenza" Member="Referenza">
    <Type Name="Referenza">
      <Column Name="VeicoloCatalogo" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ricambio" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Ricambio_Referenza" Member="Ricambio1" ThisKey="Ricambio" OtherKey="Codice" Type="Ricambio" IsForeignKey="true" />
      <Association Name="VeicoloCatalogo_Referenza" Member="VeicoloCatalogo1" ThisKey="VeicoloCatalogo" OtherKey="Codice" Type="VeicoloCatalogo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Revisione" Member="Revisione">
    <Type Name="Revisione">
      <Column Name="VeicoloVenduto" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Numero" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Scadenza" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataEsecuzione" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="VeicoloVenduto_Revisione" Member="VeicoloVenduto1" ThisKey="VeicoloVenduto" OtherKey="Id" Type="VeicoloVenduto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ricambio" Member="Ricambio">
    <Type Name="Ricambio">
      <Column Name="Codice" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PrezzoUnitarioRiparazione" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="TipoRicambio" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Fornitore" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Association Name="Ricambio_Giacenza" Member="Giacenza" ThisKey="Codice" OtherKey="Ricambio" Type="Giacenza" />
      <Association Name="Ricambio_OrdineRicambio" Member="OrdineRicambio" ThisKey="Codice" OtherKey="Ricambio" Type="OrdineRicambio" />
      <Association Name="Ricambio_Referenza" Member="Referenza" ThisKey="Codice" OtherKey="Ricambio" Type="Referenza" />
      <Association Name="Ricambio_Utilizzo" Member="Utilizzo" ThisKey="Codice" OtherKey="Ricambio" Type="Utilizzo" />
      <Association Name="Fornitore_Ricambio" Member="Fornitore1" ThisKey="Fornitore" OtherKey="PartitaIVA" Type="Fornitore" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Riparazione" Member="Riparazione">
    <Type Name="Riparazione">
      <Column Name="Veicolo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Numero" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ImportoComplessivo" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Riparazione_Utilizzo" Member="Utilizzo" ThisKey="Veicolo,Numero" OtherKey="Veicolo,Numero" Type="Utilizzo" />
      <Association Name="VeicoloVenduto_Riparazione" Member="VeicoloVenduto" ThisKey="Veicolo" OtherKey="Id" Type="VeicoloVenduto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supporto" Member="Supporto">
    <Type Name="Supporto">
      <Column Name="VeicoloCatalogo" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Optional" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Optional_Supporto" Member="Optional1" ThisKey="Optional" OtherKey="Codice" Type="Optional" IsForeignKey="true" />
      <Association Name="VeicoloCatalogo_Supporto" Member="VeicoloCatalogo1" ThisKey="VeicoloCatalogo" OtherKey="Codice" Type="VeicoloCatalogo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trasporto" Member="Trasporto">
    <Type Name="Trasporto">
      <Column Name="Codice" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Costo" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DataConsegnaPrevista" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataConsegna" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IndirizzoConsegna" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CittàConsegna" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ProvinciaConsegna" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Corriere" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="ContrattoNumero" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="ContrattoVendita_Trasporto" Member="ContrattoVendita" ThisKey="ContrattoNumero" OtherKey="Numero" Type="ContrattoVendita" IsForeignKey="true" />
      <Association Name="Corriere_Trasporto" Member="Corriere1" ThisKey="Corriere" OtherKey="PartitaIVA" Type="Corriere" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Utilizzo" Member="Utilizzo">
    <Type Name="Utilizzo">
      <Column Name="Ricambio" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Veicolo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Numero" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantità" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Association Name="Ricambio_Utilizzo" Member="Ricambio1" ThisKey="Ricambio" OtherKey="Codice" Type="Ricambio" IsForeignKey="true" />
      <Association Name="Riparazione_Utilizzo" Member="Riparazione" ThisKey="Veicolo,Numero" OtherKey="Veicolo,Numero" Type="Riparazione" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VeicoloCatalogo" Member="VeicoloCatalogo">
    <Type Name="VeicoloCatalogo">
      <Column Name="Codice" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PrezzoBase" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Potenza" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="NumPosti" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="Consumi" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Omologazione" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CapacitàSerbatorio" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="TipoAlimentazione" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cilindrata" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Trazione" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cambio" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CapienzaBagagliaio" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="NumPorte" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="NomeModello" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AnnoModello" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
      <Column Name="CasaProduttrice" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Association Name="VeicoloCatalogo_Referenza" Member="Referenza" ThisKey="Codice" OtherKey="VeicoloCatalogo" Type="Referenza" />
      <Association Name="VeicoloCatalogo_Supporto" Member="Supporto" ThisKey="Codice" OtherKey="VeicoloCatalogo" Type="Supporto" />
      <Association Name="VeicoloCatalogo_VeicoloVenduto" Member="VeicoloVenduto" ThisKey="Codice" OtherKey="VeicoloCatalogo" Type="VeicoloVenduto" />
      <Association Name="ModelloVeicolo_VeicoloCatalogo" Member="ModelloVeicolo" ThisKey="NomeModello,AnnoModello,CasaProduttrice" OtherKey="Nome,Anno,CasaProduttrice" Type="ModelloVeicolo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VeicoloVenduto" Member="VeicoloVenduto">
    <Type Name="VeicoloVenduto">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Telaio" Type="System.String" DbType="Char(17)" CanBeNull="true" />
      <Column Name="Contratto" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="VeicoloCatalogo" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="VeicoloVenduto_Dotazione" Member="Dotazione" ThisKey="Id" OtherKey="Veicolo" Type="Dotazione" />
      <Association Name="VeicoloVenduto_OrdineVeicolo" Member="OrdineVeicolo" ThisKey="Id" OtherKey="Veicolo" Type="OrdineVeicolo" Cardinality="One" />
      <Association Name="VeicoloVenduto_Revisione" Member="Revisione" ThisKey="Id" OtherKey="VeicoloVenduto" Type="Revisione" />
      <Association Name="VeicoloVenduto_Riparazione" Member="Riparazione" ThisKey="Id" OtherKey="Veicolo" Type="Riparazione" />
      <Association Name="ContrattoVendita_VeicoloVenduto" Member="ContrattoVendita" ThisKey="Contratto" OtherKey="Numero" Type="ContrattoVendita" IsForeignKey="true" />
      <Association Name="VeicoloCatalogo_VeicoloVenduto" Member="VeicoloCatalogo1" ThisKey="VeicoloCatalogo" OtherKey="Codice" Type="VeicoloCatalogo" IsForeignKey="true" />
    </Type>
  </Table>
</Database>